motron:
  title: Motron Rules!
  debug: true
  port: 9000
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:key/public_key.pem
  logging:
    level:
      presentation.reset.controllers.FooRestController: INFO

database:
  type: mongo
  mode: standalone  # or "server"
  mongo:
    uri: "mongodb://localhost:27017"
    name: "motron"
    username: "motron"
    password: 123
